## H2 사용
baseurl:
  url: http://localhost

spring:
  config:
    active:
      on-profile: dev
  datasource:
    url: jdbc:h2:tcp://localhost/~/Desktop/OneDrive/2024/pposonggil_v2/Docker/usedStuff
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

cloud:
  aws:
    s3:
      bucket: pposonggil-bucket
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key: ${api-key.s3-access-key}
      secret-key: ${api-key.s3-secret-key}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
