api-key:
  s3-access-key: AKIA47CRUJYYFLBHYHW6
  s3-secret-key: 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
  ODsay-key: OgfnH+uioYm7I1OTW0bPUc9rtGEQlu53sffC7Iu7s0c

mysql:
  username: pposong
  password: 000000

oauth:
  googleid: 839889734751-6t0ekmp3kkpq2irfsor4kdb3ldf6rvnp.apps.googleusercontent.com
  googlesecret: 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
  kakaoid: d5a41a5ef93929a398cc071f2f52ba2c
  kakaosecret: QcRSNj6zsRTWsrtbcliIEdONCEnTvj41
  jwtkey: SecretKeySecretKeySecretKeySecretKeySecretKeySecretKeySecretKeySecretKeySecretKeySecretKeySecretKeySecretKeySecretKeySecretKeySecretKeySecretKeySecretKeySecretKeySecretKeySecretKeySecretKeySecretKeySecretKeySecretKeySecretKeySecretKeySecretKeySecretKey
